This system,  right now,  depends on the virtuoso Jena drivers.  In the long
term I'd like to dynamically load the drivers at runtime so you don't need
the drivers for any particular product to run the tests,  but now you need
to load a 3rd party JAR to install this

http://virtuoso.openlinksw.com/dataspace/dav/wiki/Main/VOSDownload#Jena%20Provider

Download the virt_jena.jar and virtjdbc3.jar files.

Do

$ mvn install:install-file -Dfile=virtjdbc3.jar -DgroupId=com.openlink -DartifactId=virtjdbc3 -Dversion=6.1.5 -Dpackaging=jar
$ mvn install:install-file -Dfile=virt_jena.jar -DgroupId=com.openlink -DartifactId=virt_jena -Dversion=6.1.5 -Dpackaging=jar

at this point you'll be ready to build and run the tests.
